version: '3'
volumes:
  psql:
services:
  psql:
    image: postgres # this uses the 'latest' version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example # only do this in development
    volumes:
      - psql:/var/lib/postgresql/logger # save data between restarts
    ports:
      - 5556:5432 # binds port 5556 on your computer to the postgres port!
